services:
  - type: web
    name: secureattend-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend/
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
